In [6]:
import tensorflow as tf
import numpy as np

In [7]:
#cDefining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[34, 8], [321, 47]])

In [8]:
tensor_20

<tf.Tensor: id=1, shape=(2, 2), dtype=int32, numpy=
array([[ 34,   8],
       [321,  47]], dtype=int32)>

In [9]:
# Getting values straight from a TensorFlow constant to numpy - without session
tensor_20.numpy()

array([[ 34,   8],
       [321,  47]], dtype=int32)

In [11]:
# We are able to convert a numpy matrix back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])
tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: id=2, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

In [12]:
# Another tensor
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=3, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [13]:
# Addition between scalar and tensor
tensor + 2

<tf.Tensor: id=5, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>