In [6]:
import tensorflow as tf
import numpy as np

In [7]:
# Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[34, 8], [321, 47]])

In [8]:
tensor_20

<tf.Tensor: id=1, shape=(2, 2), dtype=int32, numpy=
array([[ 34,   8],
       [321,  47]], dtype=int32)>

In [9]:
# Getting values straight from a TensorFlow constant to numpy - without session
tensor_20.numpy()

array([[ 34,   8],
       [321,  47]], dtype=int32)

In [11]:
# We are able to convert a numpy matrix back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])
tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: id=2, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

In [12]:
# Another tensor
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=3, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [13]:
# Addition between scalar and tensor
tensor + 2

<tf.Tensor: id=5, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [16]:
# Multiplication between scalar and tensor
tensor * 4

<tf.Tensor: id=9, shape=(2, 2), dtype=int32, numpy=
array([[ 4,  8],
       [12, 16]], dtype=int32)>

### Using Numpy functions on TensorFlow tensors

In [17]:
 #Squaring all numbers in a Tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [18]:
# Square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [20]:
# Dot product between two tensors
np.dot(tensor, tensor_20)

array([[ 676,  102],
       [1386,  212]], dtype=int32)

### Operations with variables

In [21]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [22]:
# Getting raw value from the variable
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [23]:
# Changing specific value in the TensorFlow variable
tf2_variable[0, 2].assign(55)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1.,  2., 55.],
       [ 4.,  5.,  6.]], dtype=float32)>

In [24]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 1.,  2., 55.],
       [ 4.,  5.,  6.]], dtype=float32)>

In [27]:
### Strings in TensorFlow 2.0
tf_string = tf.constant("TensorFlow 2 is great")
tf_string

<tf.Tensor: id=30, shape=(), dtype=string, numpy=b'TensorFlow 2 is great'>

### Simple string operations

In [28]:
tf.strings.length(tf_string)

<tf.Tensor: id=31, shape=(), dtype=int32, numpy=21>

In [29]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=35, shape=(21,), dtype=int32, numpy=
array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119,  32,  50,  32,
       105, 115,  32, 103, 114, 101,  97, 116], dtype=int32)>

### Storing arrays of strings

In [31]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [32]:
# How to iterate through the TF string array
for string in tf_string_array:
    print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


### Handling Devices in TensorFlow 2.0

In [40]:
# CPU
with tf.device("/cpu:0"):
    tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
tf_string_array.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [41]:
# GPU
# Is GPU available?
print(tf.test.is_gpu_available())

False


In [42]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
    print(tf_string_array.device)